[16:10:09]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16:10:32]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16:11:00]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16:13:36]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16:14:11]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16:17:05]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[18:07:06]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[18:38:56]{/mnt/66D6307CD6304E95/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:20:39]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:23:50]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:23:50] "[37mGET / HTTP/1.1[0m" 200 -
[13:23:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py:1892}ERROR- Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html
[13:23:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:23:51] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[13:23:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}ERROR- Error on request:
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 23, in error_500
    return render_template('errors/500.html'), 500
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/500.html
[13:25:09]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:25:19]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:25:19] "[37mGET / HTTP/1.1[0m" 200 -
[13:25:19]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py:1892}ERROR- Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/templates/errors/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: layout.html
[13:25:19]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:25:19] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[13:25:19]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}ERROR- Error on request:
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/templates/errors/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: layout.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 23, in error_500
    return render_template('errors/500.html'), 500
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/templates/errors/500.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: layout.html
[13:26:37]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:26:41]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:26:41] "[37mGET / HTTP/1.1[0m" 200 -
[13:26:41]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py:1892}ERROR- Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html
[13:26:41]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:26:41] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[13:26:41]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}ERROR- Error on request:
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 23, in error_500
    return render_template('errors/500.html'), 500
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/500.html
[13:27:25]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:27:26]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:27:26] "[37mGET / HTTP/1.1[0m" 200 -
[13:27:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py:1892}ERROR- Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html
[13:27:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:27:27] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[13:27:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}ERROR- Error on request:
Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 10, in error_404
    return render_template('errors/404.html'), 404
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/errors/handlers.py", line 23, in error_500
    return render_template('errors/500.html'), 500
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: errors/500.html
[13:36:24]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:36:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:36:27] "[37mGET / HTTP/1.1[0m" 200 -
[13:36:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:36:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[13:36:31]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:36:31] "[37mGET / HTTP/1.1[0m" 200 -
[13:36:31]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:36:31] "[37mGET / HTTP/1.1[0m" 200 -
[13:36:43]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:36:43] "[33mGET /sdfg HTTP/1.1[0m" 404 -
[13:39:48]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[13:40:15]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 13:40:15] "[33mGET /sdfg HTTP/1.1[0m" 404 -
[15:19:45]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[15:24:34]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[15:25:49]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[15:28:04]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[15:28:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:28:07] "[31m[1mGET /api/user/register HTTP/1.1[0m" 405 -
[15:28:12]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:28:12] "[31m[1mGET /api/user/register HTTP/1.1[0m" 405 -
[15:30:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[15:30:26]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:30:26] "[31m[1mGET /api/user/register HTTP/1.1[0m" 405 -
[15:31:20]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:31:20]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:31:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:31:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:31:26]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:31:26] "[31m[1mGET /api/user/register HTTP/1.1[0m" 405 -
[15:34:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:34:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:34:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:34:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:34:25]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:34:25] "[35m[1mGET /api/user/register HTTP/1.1[0m" 500 -
[15:35:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/helpers.py', reloading
[15:35:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:35:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:35:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:35:31]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/helpers.py', reloading
[15:35:31]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:35:32]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:35:32]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:35:34]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:35:34]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:35:35]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:35:35]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:35:36]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:35:36] "[35m[1mGET /api/user/register HTTP/1.1[0m" 500 -
[15:35:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/helpers.py', reloading
[15:35:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:35:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:35:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:35:57]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:35:57] "[31m[1mGET /api/user/register HTTP/1.1[0m" 405 -
[15:36:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:36:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:36:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:36:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:36:24]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:36:24]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:36:25]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:36:25]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:36:39]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:36:39] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:37:12]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:37:12]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:37:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:37:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:37:29]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:37:29]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:37:31]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:37:31] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:38:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:38:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:38:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:38:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:38:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:38:11] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:39:00]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:39:00] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:39:54]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:39:54]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:39:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:39:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:40:12]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:40:12] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:40:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:40:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:40:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:40:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:40:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:40:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:40:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:40:55]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:40:58]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:40:58] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:41:13]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:41:13]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:41:13]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:41:13]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:41:46]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:41:46] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:42:16]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[15:42:16]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:42:16]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:42:16]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:42:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:42:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:42:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:42:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:42:46]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:42:46] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:45:06]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:45:06]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:45:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:45:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:45:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:45:11] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:45:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[15:45:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:45:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:45:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:45:36]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:45:36]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:45:37]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:45:37]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:45:38]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 15:45:38] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[15:46:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[15:46:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:46:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:46:52]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:46:54]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[15:46:54]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:54:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:54:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:54:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:54:44]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:55:10]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[15:55:10]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:55:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:55:11]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:55:29]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[15:55:29]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:55:30]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:55:30]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[15:55:46]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[15:55:46]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:58:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[15:58:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[15:58:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[15:58:08]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:00:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:00:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:00:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:00:23]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:00:27]{/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- type object 'datetime.datetime' has no attribute 'datetime'
[16:00:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:00:27] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:02:14]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:02:15]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:03:17]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:03:17]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:03:17]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:03:17]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:03:22]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:03:22] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:03:29]{/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- type object 'datetime.datetime' has no attribute 'timedelta'
[16:03:29]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:03:29] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:04:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:04:27]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:04:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:04:28]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:04:33]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:04:33]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:04:34]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:04:34]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:04:48]{/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- name 'jwt' is not defined
[16:04:48]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:04:48] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:05:09]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:05:09]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:05:10]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:05:10]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:05:18]{/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- module 'jwt' has no attribute 'encode'
[16:05:18]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:05:18] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:06:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[16:06:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:06:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:06:21]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:06:24]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:06:24] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:06:47]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:06:47]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:06:47]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:06:47]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:06:49]{/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- module 'jwt' has no attribute 'encode'
[16:06:49]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:06:49] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:07:26]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[16:07:26]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:07:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:07:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:07:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[16:07:51]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:07:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:07:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:08:06] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[16:08:07]{/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:08:07] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:08:07] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:09:00] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:09:00] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:09:00] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:09:00] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:09:23] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:09:23] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:09:30] {/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:44}INFO- module 'jwt' has no attribute 'encode'
[16:09:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:09:30] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:12:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:12:11] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:12:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:12:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:12:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:12:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:13:09] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:13:09] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:14:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[16:14:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:14:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:14:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:15:03] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:15:03] "[37mPOST /api/user/register HTTP/1.1[0m" 200 -
[16:16:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:16:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:16:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:16:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:16:31] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:16:31] "[37mPOST /api/user/register HTTP/1.1[0m" 201 -
[16:16:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:16:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:16:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:16:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:16:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:16:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:16:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:16:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:21:44] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:21:44] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:21:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:21:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:22:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:22:19] "[31m[1mGET /api/user/login HTTP/1.1[0m" 405 -
[16:22:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:22:24] "[37mPOST /api/user/login HTTP/1.1[0m" 200 -
[16:22:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:22:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:22:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:22:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:22:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:22:38] "[37mPOST /api/user/login HTTP/1.1[0m" 200 -
[16:22:48] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:22:48] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:22:49] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:22:49] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:22:50] {/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:82}INFO- Successfully logged in -'prakhar1@mailinator.com'
[16:22:50] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:22:50] "[37mPOST /api/user/login HTTP/1.1[0m" 200 -
[16:23:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:23:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:23:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:23:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:23:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:23:53] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:23:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:23:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:25:00] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:25:00] "[31m[1mGET /api/user/logout HTTP/1.1[0m" 405 -
[16:25:03] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:25:03] "[35m[1mPOST /api/user/logout HTTP/1.1[0m" 500 -
[16:25:41] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:25:42] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:25:42] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:25:42] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:25:49] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:25:49] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:25:50] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:25:50] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:26:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:26:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:26:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:26:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:26:31] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:26:31] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:26:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:26:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:26:36] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:26:36] "[35m[1mPOST /api/user/logout HTTP/1.1[0m" 500 -
[16:28:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:28:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:28:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:28:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:28:20] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:28:20] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:28:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:28:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:28:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:28:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:28:43] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:28:43] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:28:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:28:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:28:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:28:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:28:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:28:52] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:29:12] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:29:13] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:29:13] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:29:13] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:29:15] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:29:15] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:30:42] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:30:42] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:30:43] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:30:43] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:30:44] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:30:44] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:32:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:32:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:32:20] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:32:20] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:32:29] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:32:29] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:32:29] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:32:29] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:32:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:32:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:32:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:32:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:32:56] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:32:56] "[35m[1mPOST /api/user/logout HTTP/1.1[0m" 500 -
[16:33:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:33:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:33:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:33:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:33:29] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:33:29] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:34:02] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:34:02] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:34:02] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:34:02] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:34:05] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:34:05] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:34:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:34:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:34:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:34:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:34:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:34:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:34:47] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:34:47] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:34:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:34:51] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:35:10] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:35:10] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:35:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:35:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:35:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:35:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:35:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:35:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:35:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:35:30] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:35:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:35:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:35:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:35:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:35:40] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:35:40] "[33mPOST /api/user/logout HTTP/1.1[0m" 404 -
[16:36:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/core/imdb_decorator.py', reloading
[16:36:54] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:36:55] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:36:55] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:36:57] {/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:119}ERROR- 'User' object has no attribute 'save'
[16:36:57] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:36:57] "[37mPOST /api/user/logout HTTP/1.1[0m" 200 -
[16:38:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[16:38:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:38:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:38:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:38:59] {/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py:116}INFO- Successfully logged out. -'prakhar1@mailinator.com'
[16:38:59] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO- 127.0.0.1 - - [09/Jan/2021 16:38:59] "[37mPOST /api/user/logout HTTP/1.1[0m" 200 -
[16:39:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:39:17] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:39:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:39:18] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:39:56] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:39:57] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:39:57] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:39:57] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:40:10] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/models.py', reloading
[16:40:10] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:40:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:40:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[16:44:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[16:44:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[16:44:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[16:44:27] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[17:37:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/auth.py', reloading
[17:37:19] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[17:37:20] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[17:37:20] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[17:37:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[17:37:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[17:37:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[17:37:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[17:37:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[17:37:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[17:37:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[17:37:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[17:44:05] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[17:44:06] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[18:09:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[18:09:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[18:09:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[18:09:46] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[18:09:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[18:09:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[18:09:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[18:09:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 187-078-538
[21:46:32] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[21:46:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[21:46:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[21:46:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[21:46:38] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[21:51:36] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[21:51:36] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[21:51:37] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[21:51:37] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[21:56:07] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[21:56:07] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[21:56:08] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[21:56:08] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:02:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/routes/movies.py', reloading
[22:02:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:11:44] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[22:11:44] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:11:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:11:45] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:12:04] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:12:05] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:12:05] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:12:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:12:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:12:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:12:26] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:12:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:12:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:12:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:12:30] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:12:39] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:12:39] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:12:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[22:12:51] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:12:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:12:52] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:13:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:13:11] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:13:12] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:13:12] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:14:23] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:14:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:14:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:14:24] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
[22:14:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Detected change in '/home/yajant/Downloads/imdb_fynd_app/imdb_fynd_app/__init__.py', reloading
[22:14:34] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Restarting with stat
[22:14:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}WARNING-  * Debugger is active!
[22:14:35] {/home/yajant/Downloads/imdb_fynd_app/.env3/lib/python3.6/site-packages/werkzeug/_internal.py:113}INFO-  * Debugger PIN: 239-621-943
